### ISSUE TITLE
CardMetadataResponse missing field Currency

### ISSUE THREAD

**Issue by Tougee** [checkout/checkout-sdk-go#107]
Hi, I am using this SDK to implement the payout functionality, and I found that the [CardMetadataResponse](https://github.com/checkout/checkout-sdk-go/blob/master/metadata/metadata.go#L54) structure is missing the `currency` field. According to the [API documentation](https://api-reference.checkout.com/#operation/requestCardMetadata!c=200&path=currency&t=response), this field should be present. Could you please add this field as soon as possible? Thank you.

**Comment by armando-rodriguez-cko** [comment]
Thank you @Tougee, we will implement it next release

**Comment by Tougee** [comment]
Seems one more typo, this [json value](https://github.com/checkout/checkout-sdk-go/blob/master/forex/forex.go#L55) should be `rates`, according to the [API doc](https://github.com/checkout/checkout-sdk-go/blob/master/forex/forex.go#L55)

**Comment by Tougee** [comment]
One more for [CardMetadataResponse](https://github.com/checkout/checkout-sdk-go/blob/master/metadata/metadata.go#L82), this type should be an [array](https://api-reference.checkout.com/#operation/requestCardMetadata!c=200&path=local_schemes&t=response)

**Comment by armando-rodriguez-cko** [comment]
Thank you so much @Tougee! We will update them in the next release

**Comment by armando-rodriguez-cko** [comment]
Property added, we close the issue, new release will be published soon.
