### ISSUE TITLE
Support CheckoutPlatform

### ISSUE THREAD

**Issue by ehsannm** [checkout/checkout-sdk-go#16]
Hi,

Do you have any plan to support CheckoutPlatform and Transfer apis ?

**Comment by ehsannm** [comment]
I created a PR for this

**Comment by Armando-Ibarra** [comment]
Hey @ehsannm 
We just released a new version which includes tons of new functionalities.
Please let us know if you have any issue, sorry if your issue and your PR was not attended at the right time, we are just jumping on the ownership of GO SDK right now.

I'm going to close this issue, but feel free to reopen if needed
