### ISSUE TITLE
Installation instructions contain incorrect Github URL

### ISSUE THREAD

**Issue by michael-taylor-cko** [checkout/checkout-sdk-go#49]
The Module Installer directions in the [Readme](https://github.com/checkout/checkout-sdk-go/blob/master/README.md) contain the following URL for the SDK:

`github.com/checkout-sdk-go@{version}`

This is incorrect as it does not contain the organization name.  It should be:

`github.com/checkout/checkout-sdk-go@{version}`

The Import code snippet should similarly be updated.

**Comment by Armando-Ibarra** [comment]
Hi @michael-taylor-cko, this was solved on #53  let us know if you face any other issue.
